name: all_helps_dfg_win_25
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  equatable: ^2.0.5
  json_annotation: ^4.8.0
  firebase_dart: ^1.0.11
  jaguar_jwt: ^3.0.0

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
  json_serializable: ^6.7.0
  build_runner: ^2.4.0

